#########################################################
# GENERATED FILE - DO NOT EDIT
# Safe to regenerate at any time 
#########################################################
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from familyhub.models.base_model import Model
from familyhub.models.reward import Reward
from familyhub import util

from familyhub.models.reward import Reward  # noqa: E501

class CreateJob(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, reward=None, summary=None, title=None, name=None, created_at=None, updated_at=None, id=None):  # noqa: E501
        """CreateJob - a model defined in OpenAPI

        :param reward: The reward of this CreateJob.  # noqa: E501
        :type reward: Reward
        :param summary: The summary of this CreateJob.  # noqa: E501
        :type summary: str
        :param title: The title of this CreateJob.  # noqa: E501
        :type title: str
        :param name: The name of this CreateJob.  # noqa: E501
        :type name: str
        :param created_at: The created_at of this CreateJob.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this CreateJob.  # noqa: E501
        :type updated_at: datetime
        :param id: The id of this CreateJob.  # noqa: E501
        :type id: str
        """
        self.openapi_types = {
            'reward': Reward,
            'summary': str,
            'title': str,
            'name': str,
            'created_at': datetime,
            'updated_at': datetime,
            'id': str
        }

        self.attribute_map = {
            'reward': 'reward',
            'summary': 'summary',
            'title': 'title',
            'name': 'name',
            'created_at': 'created_at',
            'updated_at': 'updated_at',
            'id': 'id'
        }

        self._reward = reward
        self._summary = summary
        self._title = title
        self._name = name
        self._created_at = created_at
        self._updated_at = updated_at
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'CreateJob':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateJob of this CreateJob.  # noqa: E501
        :rtype: CreateJob
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reward(self) -> Reward:
        """Gets the reward of this CreateJob.


        :return: The reward of this CreateJob.
        :rtype: Reward
        """
        return self._reward

    @reward.setter
    def reward(self, reward: Reward):
        """Sets the reward of this CreateJob.


        :param reward: The reward of this CreateJob.
        :type reward: Reward
        """
        if reward is None:
            raise ValueError("Invalid value for `reward`, must not be `None`")  # noqa: E501

        self._reward = reward

    @property
    def summary(self) -> str:
        """Gets the summary of this CreateJob.

        additional information on the requirements of the job  # noqa: E501

        :return: The summary of this CreateJob.
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary: str):
        """Sets the summary of this CreateJob.

        additional information on the requirements of the job  # noqa: E501

        :param summary: The summary of this CreateJob.
        :type summary: str
        """

        self._summary = summary

    @property
    def title(self) -> str:
        """Gets the title of this CreateJob.

        title for the job  # noqa: E501

        :return: The title of this CreateJob.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this CreateJob.

        title for the job  # noqa: E501

        :param title: The title of this CreateJob.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501
        if title is not None and len(title) > 255:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `255`")  # noqa: E501

        self._title = title

    @property
    def name(self) -> str:
        """Gets the name of this CreateJob.

        user's name  # noqa: E501

        :return: The name of this CreateJob.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CreateJob.

        user's name  # noqa: E501

        :param name: The name of this CreateJob.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this CreateJob.

        when the record was created  # noqa: E501

        :return: The created_at of this CreateJob.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this CreateJob.

        when the record was created  # noqa: E501

        :param created_at: The created_at of this CreateJob.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this CreateJob.

        when the record was last updated  # noqa: E501

        :return: The updated_at of this CreateJob.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this CreateJob.

        when the record was last updated  # noqa: E501

        :param updated_at: The updated_at of this CreateJob.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def id(self) -> str:
        """Gets the id of this CreateJob.

        user id  # noqa: E501

        :return: The id of this CreateJob.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this CreateJob.

        user id  # noqa: E501

        :param id: The id of this CreateJob.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id
