#########################################################
# GENERATED FILE - DO NOT EDIT
# Safe to regenerate at any time 
#########################################################
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from familyhub.models.base_model import Model
from familyhub.models.reward import Reward
from familyhub.models.user import User
from familyhub import util

from familyhub.models.reward import Reward  # noqa: E501
from familyhub.models.user import User  # noqa: E501

class Job(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, reward=None, summary=None, title=None, name=None, created_at=None, updated_at=None, id=None, closed_at=None, claimed_by=None, status=None):  # noqa: E501
        """Job - a model defined in OpenAPI

        :param reward: The reward of this Job.  # noqa: E501
        :type reward: Reward
        :param summary: The summary of this Job.  # noqa: E501
        :type summary: str
        :param title: The title of this Job.  # noqa: E501
        :type title: str
        :param name: The name of this Job.  # noqa: E501
        :type name: str
        :param created_at: The created_at of this Job.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Job.  # noqa: E501
        :type updated_at: datetime
        :param id: The id of this Job.  # noqa: E501
        :type id: str
        :param closed_at: The closed_at of this Job.  # noqa: E501
        :type closed_at: datetime
        :param claimed_by: The claimed_by of this Job.  # noqa: E501
        :type claimed_by: User
        :param status: The status of this Job.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'reward': Reward,
            'summary': str,
            'title': str,
            'name': str,
            'created_at': datetime,
            'updated_at': datetime,
            'id': str,
            'closed_at': datetime,
            'claimed_by': User,
            'status': str
        }

        self.attribute_map = {
            'reward': 'reward',
            'summary': 'summary',
            'title': 'title',
            'name': 'name',
            'created_at': 'created_at',
            'updated_at': 'updated_at',
            'id': 'id',
            'closed_at': 'closed_at',
            'claimed_by': 'claimed_by',
            'status': 'status'
        }

        self._reward = reward
        self._summary = summary
        self._title = title
        self._name = name
        self._created_at = created_at
        self._updated_at = updated_at
        self._id = id
        self._closed_at = closed_at
        self._claimed_by = claimed_by
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Job':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Job of this Job.  # noqa: E501
        :rtype: Job
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reward(self) -> Reward:
        """Gets the reward of this Job.


        :return: The reward of this Job.
        :rtype: Reward
        """
        return self._reward

    @reward.setter
    def reward(self, reward: Reward):
        """Sets the reward of this Job.


        :param reward: The reward of this Job.
        :type reward: Reward
        """
        if reward is None:
            raise ValueError("Invalid value for `reward`, must not be `None`")  # noqa: E501

        self._reward = reward

    @property
    def summary(self) -> str:
        """Gets the summary of this Job.

        additional information on the requirements of the job  # noqa: E501

        :return: The summary of this Job.
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary: str):
        """Sets the summary of this Job.

        additional information on the requirements of the job  # noqa: E501

        :param summary: The summary of this Job.
        :type summary: str
        """
        if summary is None:
            raise ValueError("Invalid value for `summary`, must not be `None`")  # noqa: E501

        self._summary = summary

    @property
    def title(self) -> str:
        """Gets the title of this Job.

        title for the job  # noqa: E501

        :return: The title of this Job.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Job.

        title for the job  # noqa: E501

        :param title: The title of this Job.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501
        if title is not None and len(title) > 255:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `255`")  # noqa: E501

        self._title = title

    @property
    def name(self) -> str:
        """Gets the name of this Job.

        user's name  # noqa: E501

        :return: The name of this Job.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Job.

        user's name  # noqa: E501

        :param name: The name of this Job.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Job.

        when the record was created  # noqa: E501

        :return: The created_at of this Job.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Job.

        when the record was created  # noqa: E501

        :param created_at: The created_at of this Job.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Job.

        when the record was last updated  # noqa: E501

        :return: The updated_at of this Job.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Job.

        when the record was last updated  # noqa: E501

        :param updated_at: The updated_at of this Job.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def id(self) -> str:
        """Gets the id of this Job.

        quest unique identifier  # noqa: E501

        :return: The id of this Job.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Job.

        quest unique identifier  # noqa: E501

        :param id: The id of this Job.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def closed_at(self) -> datetime:
        """Gets the closed_at of this Job.

        When the job reached a terminal state (completed or voided). Null if not terminal.   # noqa: E501

        :return: The closed_at of this Job.
        :rtype: datetime
        """
        return self._closed_at

    @closed_at.setter
    def closed_at(self, closed_at: datetime):
        """Sets the closed_at of this Job.

        When the job reached a terminal state (completed or voided). Null if not terminal.   # noqa: E501

        :param closed_at: The closed_at of this Job.
        :type closed_at: datetime
        """

        self._closed_at = closed_at

    @property
    def claimed_by(self) -> User:
        """Gets the claimed_by of this Job.

        the one who claimed the job  # noqa: E501

        :return: The claimed_by of this Job.
        :rtype: User
        """
        return self._claimed_by

    @claimed_by.setter
    def claimed_by(self, claimed_by: User):
        """Sets the claimed_by of this Job.

        the one who claimed the job  # noqa: E501

        :param claimed_by: The claimed_by of this Job.
        :type claimed_by: User
        """

        self._claimed_by = claimed_by

    @property
    def status(self) -> str:
        """Gets the status of this Job.

        available - a user posted a job that can be accepted   by any other user inprogress - a user claims the job and is working on   the it completed - once the job poster is satisfied with the work of   the job claimer and then given the reward then the job   is deemed complete voided - job poster voided the job and can no longer be   accepted by any user   # noqa: E501

        :return: The status of this Job.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Job.

        available - a user posted a job that can be accepted   by any other user inprogress - a user claims the job and is working on   the it completed - once the job poster is satisfied with the work of   the job claimer and then given the reward then the job   is deemed complete voided - job poster voided the job and can no longer be   accepted by any user   # noqa: E501

        :param status: The status of this Job.
        :type status: str
        """
        allowed_values = ["available", "inprogress", "completed", "voided"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
