#########################################################
# GENERATED FILE - DO NOT EDIT
# Safe to regenerate at any time 
#########################################################
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from familyhub.models.base_model import Model
from familyhub.models.reward import Reward
from familyhub import util

from familyhub.models.reward import Reward  # noqa: E501

class JobBase(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, reward=None, summary=None, title=None):  # noqa: E501
        """JobBase - a model defined in OpenAPI

        :param reward: The reward of this JobBase.  # noqa: E501
        :type reward: Reward
        :param summary: The summary of this JobBase.  # noqa: E501
        :type summary: str
        :param title: The title of this JobBase.  # noqa: E501
        :type title: str
        """
        self.openapi_types = {
            'reward': Reward,
            'summary': str,
            'title': str
        }

        self.attribute_map = {
            'reward': 'reward',
            'summary': 'summary',
            'title': 'title'
        }

        self._reward = reward
        self._summary = summary
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'JobBase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobBase of this JobBase.  # noqa: E501
        :rtype: JobBase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reward(self) -> Reward:
        """Gets the reward of this JobBase.


        :return: The reward of this JobBase.
        :rtype: Reward
        """
        return self._reward

    @reward.setter
    def reward(self, reward: Reward):
        """Sets the reward of this JobBase.


        :param reward: The reward of this JobBase.
        :type reward: Reward
        """

        self._reward = reward

    @property
    def summary(self) -> str:
        """Gets the summary of this JobBase.

        additional information on the requirements of the job  # noqa: E501

        :return: The summary of this JobBase.
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary: str):
        """Sets the summary of this JobBase.

        additional information on the requirements of the job  # noqa: E501

        :param summary: The summary of this JobBase.
        :type summary: str
        """

        self._summary = summary

    @property
    def title(self) -> str:
        """Gets the title of this JobBase.

        title for the job  # noqa: E501

        :return: The title of this JobBase.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this JobBase.

        title for the job  # noqa: E501

        :param title: The title of this JobBase.
        :type title: str
        """
        if title is not None and len(title) > 255:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `255`")  # noqa: E501

        self._title = title
