#########################################################
# GENERATED FILE - DO NOT EDIT
# Safe to regenerate at any time 
#########################################################
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from familyhub.models.base_model import Model
from familyhub import util


class JobAction(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, action=None):  # noqa: E501
        """JobAction - a model defined in OpenAPI

        :param action: The action of this JobAction.  # noqa: E501
        :type action: str
        """
        self.openapi_types = {
            'action': str
        }

        self.attribute_map = {
            'action': 'action'
        }

        self._action = action

    @classmethod
    def from_dict(cls, dikt) -> 'JobAction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobAction of this JobAction.  # noqa: E501
        :rtype: JobAction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def action(self) -> str:
        """Gets the action of this JobAction.

        accept - a user accepts an available job moving its   status to inprogress and the job can no longer be claimed   by other users complete - the job poster determines the job is complete void - the job poster voids the job and thus can no longer   be accepted or worked on   # noqa: E501

        :return: The action of this JobAction.
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action: str):
        """Sets the action of this JobAction.

        accept - a user accepts an available job moving its   status to inprogress and the job can no longer be claimed   by other users complete - the job poster determines the job is complete void - the job poster voids the job and thus can no longer   be accepted or worked on   # noqa: E501

        :param action: The action of this JobAction.
        :type action: str
        """
        allowed_values = ["accept", "complete", "void"]  # noqa: E501
        if action not in allowed_values:
            raise ValueError(
                "Invalid value for `action` ({0}), must be one of {1}"
                .format(action, allowed_values)
            )

        self._action = action
