#########################################################
# GENERATED FILE - DO NOT EDIT
# Safe to regenerate at any time 
#########################################################
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from familyhub.models.base_model import Model
from familyhub import util


class JobPoster(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, created_at=None, updated_at=None, id=None):  # noqa: E501
        """JobPoster - a model defined in OpenAPI

        :param name: The name of this JobPoster.  # noqa: E501
        :type name: str
        :param created_at: The created_at of this JobPoster.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this JobPoster.  # noqa: E501
        :type updated_at: datetime
        :param id: The id of this JobPoster.  # noqa: E501
        :type id: str
        """
        self.openapi_types = {
            'name': str,
            'created_at': datetime,
            'updated_at': datetime,
            'id': str
        }

        self.attribute_map = {
            'name': 'name',
            'created_at': 'created_at',
            'updated_at': 'updated_at',
            'id': 'id'
        }

        self._name = name
        self._created_at = created_at
        self._updated_at = updated_at
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'JobPoster':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobPoster of this JobPoster.  # noqa: E501
        :rtype: JobPoster
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this JobPoster.

        user's name  # noqa: E501

        :return: The name of this JobPoster.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this JobPoster.

        user's name  # noqa: E501

        :param name: The name of this JobPoster.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this JobPoster.

        when the record was created  # noqa: E501

        :return: The created_at of this JobPoster.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this JobPoster.

        when the record was created  # noqa: E501

        :param created_at: The created_at of this JobPoster.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this JobPoster.

        when the record was last updated  # noqa: E501

        :return: The updated_at of this JobPoster.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this JobPoster.

        when the record was last updated  # noqa: E501

        :param updated_at: The updated_at of this JobPoster.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def id(self) -> str:
        """Gets the id of this JobPoster.

        user id  # noqa: E501

        :return: The id of this JobPoster.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this JobPoster.

        user id  # noqa: E501

        :param id: The id of this JobPoster.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id
