#########################################################
# GENERATED FILE - DO NOT EDIT
# Safe to regenerate at any time 
#########################################################
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from familyhub.models.base_model import Model
from familyhub.models.reward_cash import RewardCash
from familyhub.models.reward_item import RewardItem
from familyhub import util

from familyhub.models.reward_cash import RewardCash  # noqa: E501
from familyhub.models.reward_item import RewardItem  # noqa: E501

class Reward(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, kind=None, amount=None, name=None, summary=None):  # noqa: E501
        """Reward - a model defined in OpenAPI

        :param kind: The kind of this Reward.  # noqa: E501
        :type kind: str
        :param amount: The amount of this Reward.  # noqa: E501
        :type amount: int
        :param name: The name of this Reward.  # noqa: E501
        :type name: str
        :param summary: The summary of this Reward.  # noqa: E501
        :type summary: str
        """
        self.openapi_types = {
            'kind': str,
            'amount': int,
            'name': str,
            'summary': str
        }

        self.attribute_map = {
            'kind': 'kind',
            'amount': 'amount',
            'name': 'name',
            'summary': 'summary'
        }

        self._kind = kind
        self._amount = amount
        self._name = name
        self._summary = summary

    @classmethod
    def from_dict(cls, dikt) -> 'Reward':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Reward of this Reward.  # noqa: E501
        :rtype: Reward
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kind(self) -> str:
        """Gets the kind of this Reward.


        :return: The kind of this Reward.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this Reward.


        :param kind: The kind of this Reward.
        :type kind: str
        """
        allowed_values = ["item"]  # noqa: E501
        if kind not in allowed_values:
            raise ValueError(
                "Invalid value for `kind` ({0}), must be one of {1}"
                .format(kind, allowed_values)
            )

        self._kind = kind

    @property
    def amount(self) -> int:
        """Gets the amount of this Reward.

        US dollar cash value  # noqa: E501

        :return: The amount of this Reward.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this Reward.

        US dollar cash value  # noqa: E501

        :param amount: The amount of this Reward.
        :type amount: int
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501
        if amount is not None and amount < 1:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must be a value greater than or equal to `1`")  # noqa: E501

        self._amount = amount

    @property
    def name(self) -> str:
        """Gets the name of this Reward.

        name of the reward item  # noqa: E501

        :return: The name of this Reward.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Reward.

        name of the reward item  # noqa: E501

        :param name: The name of this Reward.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def summary(self) -> str:
        """Gets the summary of this Reward.

        any additional informationn  # noqa: E501

        :return: The summary of this Reward.
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary: str):
        """Sets the summary of this Reward.

        any additional informationn  # noqa: E501

        :param summary: The summary of this Reward.
        :type summary: str
        """

        self._summary = summary
