#########################################################
# GENERATED FILE - DO NOT EDIT
# Safe to regenerate at any time 
#########################################################
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from familyhub.models.base_model import Model
from familyhub import util


class RewardItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, kind=None, name=None, summary=None):  # noqa: E501
        """RewardItem - a model defined in OpenAPI

        :param kind: The kind of this RewardItem.  # noqa: E501
        :type kind: str
        :param name: The name of this RewardItem.  # noqa: E501
        :type name: str
        :param summary: The summary of this RewardItem.  # noqa: E501
        :type summary: str
        """
        self.openapi_types = {
            'kind': str,
            'name': str,
            'summary': str
        }

        self.attribute_map = {
            'kind': 'kind',
            'name': 'name',
            'summary': 'summary'
        }

        self._kind = kind
        self._name = name
        self._summary = summary

    @classmethod
    def from_dict(cls, dikt) -> 'RewardItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RewardItem of this RewardItem.  # noqa: E501
        :rtype: RewardItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kind(self) -> str:
        """Gets the kind of this RewardItem.


        :return: The kind of this RewardItem.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this RewardItem.


        :param kind: The kind of this RewardItem.
        :type kind: str
        """
        allowed_values = ["item"]  # noqa: E501
        if kind not in allowed_values:
            raise ValueError(
                "Invalid value for `kind` ({0}), must be one of {1}"
                .format(kind, allowed_values)
            )

        self._kind = kind

    @property
    def name(self) -> str:
        """Gets the name of this RewardItem.

        name of the reward item  # noqa: E501

        :return: The name of this RewardItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this RewardItem.

        name of the reward item  # noqa: E501

        :param name: The name of this RewardItem.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def summary(self) -> str:
        """Gets the summary of this RewardItem.

        any additional informationn  # noqa: E501

        :return: The summary of this RewardItem.
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary: str):
        """Sets the summary of this RewardItem.

        any additional informationn  # noqa: E501

        :param summary: The summary of this RewardItem.
        :type summary: str
        """

        self._summary = summary
