#########################################################
# GENERATED FILE - DO NOT EDIT
# Safe to regenerate at any time 
#########################################################
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from familyhub.models.base_model import Model
from familyhub import util


class RewardCash(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, kind=None, amount=None):  # noqa: E501
        """RewardCash - a model defined in OpenAPI

        :param kind: The kind of this RewardCash.  # noqa: E501
        :type kind: str
        :param amount: The amount of this RewardCash.  # noqa: E501
        :type amount: int
        """
        self.openapi_types = {
            'kind': str,
            'amount': int
        }

        self.attribute_map = {
            'kind': 'kind',
            'amount': 'amount'
        }

        self._kind = kind
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'RewardCash':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RewardCash of this RewardCash.  # noqa: E501
        :rtype: RewardCash
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kind(self) -> str:
        """Gets the kind of this RewardCash.


        :return: The kind of this RewardCash.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this RewardCash.


        :param kind: The kind of this RewardCash.
        :type kind: str
        """
        allowed_values = ["cash"]  # noqa: E501
        if kind not in allowed_values:
            raise ValueError(
                "Invalid value for `kind` ({0}), must be one of {1}"
                .format(kind, allowed_values)
            )

        self._kind = kind

    @property
    def amount(self) -> int:
        """Gets the amount of this RewardCash.

        US dollar cash value  # noqa: E501

        :return: The amount of this RewardCash.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this RewardCash.

        US dollar cash value  # noqa: E501

        :param amount: The amount of this RewardCash.
        :type amount: int
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501
        if amount is not None and amount < 1:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must be a value greater than or equal to `1`")  # noqa: E501

        self._amount = amount
