#########################################################
# GENERATED FILE - DO NOT EDIT
# Safe to regenerate at any time 
#########################################################
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from familyhub.models.base_model import Model
from familyhub import util


class Timestamps(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created_at=None, updated_at=None):  # noqa: E501
        """Timestamps - a model defined in OpenAPI

        :param created_at: The created_at of this Timestamps.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Timestamps.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'created_at': 'created_at',
            'updated_at': 'updated_at'
        }

        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Timestamps':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Timestamps of this Timestamps.  # noqa: E501
        :rtype: Timestamps
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Timestamps.

        when the record was created  # noqa: E501

        :return: The created_at of this Timestamps.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Timestamps.

        when the record was created  # noqa: E501

        :param created_at: The created_at of this Timestamps.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Timestamps.

        when the record was last updated  # noqa: E501

        :return: The updated_at of this Timestamps.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Timestamps.

        when the record was last updated  # noqa: E501

        :param updated_at: The updated_at of this Timestamps.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at
